input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
downloading_params:
  s3_bucket: for-dvc
  paths:
    - train.csv
    - test.csv
  output_folder: "data/raw/"
splitting_params:
  test_size: 0.2
  random_state: 43
train_params:
  model_type: "LogisticRegression"
feature_params:
  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  target_col: "condition"
